### ISSUE TITLE
Fallback if not found on Cloudinary

### ISSUE THREAD

**Issue by clemblanco** [jrm2k6/cloudder#19]
Is there a way to have a fallback if 404 on Cloudinary?

AFAIK Cloudinary class will just generate the full URL, not make any request to check if the resource is available.

However, I'd like to have a fallback if the remote image is not found so I can display the local version of it. Unfortunately, this might imply making an extra request per image and will consume more bandwidth.

What do you think?

**Comment by jrm2k6** [comment]
Sorry, just checking those now. I will check that tonight and get back with an answer for you.

**Comment by peterhofman** [comment]
Using Cloudder for a project, and need this option to, any work in progress for this? of a solution? Tnxs!

**Comment by jrm2k6** [comment]
Oh will check. I will probably add a method that will return if a resource is currently available in your cloudinary bucket.

**Comment by jrm2k6** [comment]
@Claymm @peterhofman I feel like the best way would be:

```
try {
    $resource = Cloudder::resource('your-img-id');
} catch (\Exception $e) {
    $resource = $this->getLocalImage()
}
```

**Comment by abr4xas** [comment]
@Claymm you can use this: 

```css
img:before {
    content: "The image below is broken :(";
    display: block;
    margin-bottom: 10px;
    font-size: 14px;
    color: rgb(100, 100, 100);
}
```
Is a small css snippet to show a message if the resource isn't  available.
